#!/bin/sh -e

######Define Vairables#####
echo -n "What drive do you want to install on? ie: /dev/vda "
read device
#this line is a test-delete it
####Partition Drive####
sudo parted $device mklabel gpt
sudo parted $device mkpart ESP fat32 1MiB 513MiB
sudo parted $device set 1 boot on
sudo parted $device name 1 efi
sudo parted $device mkpart primary 513MiB 800MiB
sudo parted $device name 2 boot
sudo parted $device mkpart primary 800MiB 100%
sudo parted $device name 3 lvm
sudo parted $device set 3 lvm on
pvcreate $device"3"
vgcreate lvm $device"3"
lvcreate -n root -L 15G lvm
lvcreate -n swap -L 10G lvm
lvcreate -n home -l 100%FREE lvm
mkfs.fat -F32 $device"1"
mkfs.ext2 $device"2"
mkfs.btrfs -L root /dev/lvm/root
mkfs.btrfs -L home /dev/lvm/home
mkswap /dev/lvm/swap
swapon /dev/lvm/swap
mount /dev/lvm/root /mnt
mkdir /mnt/{home,boot}
mount $device"2" /mnt/boot
mkdir /mnt/boot/efi
mount $device"1" /mnt/boot/efi
mount /dev/lvm/home /mnt/home

####Setup Configs####
pacstrap /mnt base base-devel linux linux-firmware grub efibootmgr vim btrfs-progs --noconfirm
genfstab -U -p /mnt > /mnt/etc/fstab

#Function Buildout
Buildout(){

#Ask Questions
echo -n "What username would you like? "
read user2
echo -n "What HostName would you like? "
read host
echo -n "what is your locale?  ex: America/Phoenix "
read locale

export lang="en_US.UTF-8"
export locale="en_US.UTF-8 UTF-8"
export username=$user2


#Set information for devices/timezones
echo $hostname > /etc/hostname
ln -s /usr/share/zoneinfo/$countrycode/$timezone /etc/localtime
echo "LANG=$lang" >> /etc/locale.conf
sed -i "/$locale/s/^#//" /etc/locale.gen
locale-gen
hwclock --systohc

#Set Passwords
echo "Password for root"
passwd root
useradd -m -g users -G wheel $username
echo "Password for "$username
passwd $username

#Install base softwares
pacman -Syyu networkmanager neovim lvm2 sudo brave openssh --noconfirm

#Correct hooks to add lvm2
sed -i '/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/s/^/HOOKS=(base udev autodetect modconf block lvm2 filesystems keyboard fsck)'/ /etc/mkinitcpio.conf

#Grub install
grub-install --target=x86_64-efi --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
mkinitcpio -p linux

#Give users with Wheel sudo access
sed -i '/^# %wheel ALL=(ALL) ALL/s/^# //' /etc/sudoers

#Enable Services
systemctl enable {sshd,NetworkManager}
}
#Finish funtion
export -f Buildout

#Enter arch-chroot and run function
arch-chroot /mnt /bin/bash -c "Buildout"
echo "you can reboot now"

